services:
  invoicerr:
    image: ghcr.io/lucanori/invoicerr:latest
    container_name: invoicerr
    restart: unless-stopped
    networks:
      - invoicerr
    ports:
      - "4274:80"
    depends_on:
      - invoicerr_db
    environment:
      - DATABASE_URL=postgresql://${INVOICERR_DB_USER}:${INVOICERR_DB_PASSWORD}@invoicerr_db:5432/${INVOICERR_DB_NAME}
      - APP_URL=https://your-domain.com
      - JWT_SECRET=${INVOICERR_JWT_SECRET}
      # Optional: uncomment to enable email features
      # - SMTP_HOST=smtp-relay.example.com
      # - SMTP_USER="username@example.com"
      # - SMTP_FROM="user-from@example.com" # Not required if SMTP_USER is the same as SMTP_FROM
      # - SMTP_PASSWORD="your_smtp_password"

  invoicerr_db:
    image: postgres:latest
    user: ${PUID}:${PGID}
    container_name: invoicerr_db
    restart: unless-stopped
    networks:
      - invoicerr
    environment:
      - POSTGRES_USER=${INVOICERR_DB_USER}
      - POSTGRES_PASSWORD=${INVOICERR_DB_PASSWORD}
      - POSTGRES_DB=${INVOICERR_DB_NAME}
    volumes:
      - ${APPDATA}/invoicerr/db:/var/lib/postgresql/data

networks:
  invoicerr:
    driver: bridge